import {readFileSync,writeFileSync} from 'node:fs';
function edit(file,fn){writeFileSync(file,fn(readFileSync(file,'utf8')));}
edit('src/lib/storage.ts',s=>s.replace('(full|thumb)\\.webp','(?:(full|thumb)\\.webp|document\\.pdf)').replace('putObject(key: string, data: Buffer)','putObject(key: string, data: Buffer, mime = "image/webp")').replace('ContentType: "image/webp"','ContentType: mime'));
edit('src/lib/db.ts',s=>s.replace('db?: PrismaClient','dbV2?: PrismaClient').replaceAll('globalDb.db','globalDb.dbV2'));
edit('src/lib/pets.ts',s=>s.replace('const usage = await tx.petImage.aggregate({','const healthUsage = await tx.attachment.aggregate({where:{record:{pet:{ownerId}}},_sum:{bytes:true}});\n        const usage = await tx.petImage.aggregate({').replace('(usage._sum.bytes || 0) -','(usage._sum.bytes || 0) + (healthUsage._sum.bytes || 0) -').replace('150 MB photo allowance. Remove unused photos first.','150 MB storage allowance. Remove unused identity photos; removed medical files are retained for 30 days.'));
edit('src/app/layout.tsx',s=>s.replace('import "./globals.css";','import "./globals.css";\nimport "./health.css";'));
edit('src/components/petish-app.tsx',s=>s.replace('import PublicCard,','import HealthSpace from "./health-space";\nimport PublicCard,').replace(') : section === "pets" && id && pet && editing ? (',') : section === "pets" && id && pet && segments[3] === "health" ? (\n            <HealthSpace key={pet.id} pet={pet} ownerId={user.id} ownerName={user.name} path={segments.slice(4)} />\n          ) : section === "pets" && id && pet && editing ? (').replace('              <div className="detail-lower">','              <div className="pet-health-link"><Link className="button primary" href={`/app/pets/${pet.id}/health`}><Heart size={19}/> Health record <ArrowUpRight size={17}/></Link></div>\n              <div className="detail-lower">').replace('              <div className="home-lower">','              {activePets.length > 0 && <section className="home-health-card"><h2>A little care, kept together.</h2><p>Visits, prescriptions, and the details you want to remember.</p><div className="button-row">{activePets.slice(0,3).map(p=><Link key={p.id} className="button secondary" href={`/app/pets/${p.id}/health`}>{p.name}’s health <ArrowUpRight size={15}/></Link>)}</div></section>}\n              <div className="home-lower">'));
edit('scripts/cleanup-uploads.ts',s=>s.replace('const referenced = new Set(rows.flatMap((r) => [r.objectKey, r.thumbKey]));','const healthFiles = await db.attachment.findMany({select:{objectKey:true,thumbKey:true}});\nconst referenced = new Set([...rows.flatMap((r) => [r.objectKey, r.thumbKey]), ...healthFiles.flatMap(r=>[r.objectKey,...(r.thumbKey?[r.thumbKey]:[])])]);').replace('["full.webp", "thumb.webp"]','["full.webp", "thumb.webp", "document.pdf"]').replace('    await unlink(target);','    if(await db.attachment.findFirst({where:{OR:[{objectKey:key},{thumbKey:key}]}})) continue;\n    await unlink(target);'));
edit('src/components/health-space.tsx',s=>s.replace('useEffect,useState','useEffect,useRef,useState').replace("const [error,setError]=useState(''),[busy,setBusy]=useState(false);return <div className=\"health-context-overlay\"><section role=\"dialog\" aria-modal=\"true\" aria-labelledby=\"context-title\" className=\"health-context-editor\">", "const dialog=useRef<HTMLDialogElement>(null);useEffect(()=>{const el=dialog.current;el?.showModal();return()=>el?.close();},[]);const [error,setError]=useState(''),[busy,setBusy]=useState(false);return <dialog ref={dialog} aria-labelledby=\"context-title\" className=\"health-context-editor\" onCancel={close}>").replace('</form></section></div>;','</form></dialog>;'));
console.log('Phase 2 routes, navigation, private storage, and safe cleanup integrated.');
